# Generated by Django 5.2.12 on 2026-04-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=15)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_refrigerated', models.BooleanField(default=False)),
                ('fuel_type', models.CharField(default='diesel', max_length=10)),
                ('status', models.CharField(blank=True, max_length=14, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('registration_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicles',
                'managed': True,
            },
        ),
    ]
