# Generated by Django 5.2.12 on 2026-04-09 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0008_remove_driverprofile_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50)),
                ('license_expiry_date', models.DateField()),
                ('license_type', models.CharField(default='heavy_vehicle', max_length=20)),
                ('experience_years', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('medical_certificate_expiry', models.DateField(blank=True, null=True)),
                ('last_training_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='available', max_length=20)),
                ('employee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='api.employee')),
            ],
            options={
                'db_table': 'drivers',
                'managed': True,
            },
        ),
    ]
