# Generated by Django 5.2.12 on 2026-04-28 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_logs', to='drivers.driver')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='trip_logs', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'driver_trip_logs',
                'managed': True,
            },
        ),
    ]
