# Generated by Django 5.2.12 on 2026-04-11 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=32)),
                ('expected_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('received_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('unit_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('unit_volume_m3', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_volume_m3', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('special_handling', models.CharField(choices=[('none', 'None'), ('cooling', 'Requires cooling'), ('frozen', 'Requires freezing'), ('fragile', 'Fragile'), ('hazardous', 'Hazardous material'), ('dry_storage', 'Dry storage only')], default='none', max_length=32)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('qr_token', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InboundCollectionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted by driver'), ('en_route', 'En route to supplier'), ('at_supplier', 'At supplier'), ('verifying', 'Verifying goods'), ('returning', 'Returning to warehouse'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('tracking_mode', models.CharField(default='full', max_length=32)),
                ('vehicle_capacity_ok', models.BooleanField(default=False)),
                ('vehicle_cooling_ok', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at_supplier', models.DateTimeField(blank=True, null=True)),
                ('collection_completed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at_warehouse', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='InboundException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(choices=[('shortfall', 'Shortfall'), ('damaged_goods', 'Damaged goods'), ('wrong_goods', 'Wrong goods received'), ('supplier_absent', 'Supplier not present'), ('cooling_breach', 'Temperature/cooling issue'), ('vehicle_mismatch', 'Vehicle not suitable'), ('delay', 'Delay in transit'), ('refused', 'Collection refused')], max_length=32)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('location_lat', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('photo_urls', models.JSONField(default=list)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='inbound.inboundcollectionassignment')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_exceptions_reported', to=settings.AUTH_USER_MODEL)),
                ('manifest_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inbound.manifestlineitem')),
            ],
        ),
        migrations.CreateModel(
            name='CollectedLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('collected_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('rejected', 'Rejected — not loaded')], default='good', max_length=32)),
                ('condition_notes', models.TextField(blank=True)),
                ('scanned_qr', models.CharField(blank=True, max_length=255)),
                ('photo_urls', models.JSONField(default=list)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_items', to='inbound.inboundcollectionassignment')),
                ('manifest_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inbound.manifestlineitem')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDeliveryManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('manifest_reference', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('received', 'Manifest received'), ('planned', 'Collection planned'), ('assigned', 'Driver assigned'), ('in_transit', 'Driver in transit'), ('collected', 'Collected — returning'), ('delivered', 'Delivered to warehouse'), ('discrepancy', 'Delivered with discrepancy'), ('cancelled', 'Cancelled')], default='received', max_length=32)),
                ('expected_collection', models.DateTimeField()),
                ('destination', models.CharField(choices=[('warehouse', 'Main warehouse'), ('production', 'Production floor')], default='warehouse', max_length=32)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_volume_m3', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('special_handling', models.CharField(choices=[('none', 'None'), ('cooling', 'Requires cooling'), ('frozen', 'Requires freezing'), ('fragile', 'Fragile'), ('hazardous', 'Hazardous material'), ('dry_storage', 'Dry storage only')], default='none', max_length=32)),
                ('temperature_min_c', models.DecimalField(blank=True, decimal_places=1, help_text='Required if special_handling is cooling or frozen', max_digits=5, null=True)),
                ('temperature_max_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('supplier_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifests', to='inbound.supplier')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='manifestlineitem',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='inbound.supplierdeliverymanifest'),
        ),
        migrations.AddField(
            model_name='inboundcollectionassignment',
            name='manifest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='inbound.supplierdeliverymanifest'),
        ),
    ]
