# Generated by Django 5.2.12 on 2026-04-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundcollectionassignment',
            name='dock_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='inboundcollectionassignment',
            name='scheduled_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
