# Generated by Django 5.2.12 on 2026-04-10 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('qr_token', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('po_reference', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned'), ('in_transit', 'In transit'), ('partially_received', 'Partially received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('expected_pickup', models.DateTimeField()),
                ('destination', models.CharField(choices=[('warehouse', 'Warehouse'), ('production', 'Production floor')], default='warehouse', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.warehouse')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='POLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=32)),
                ('ordered_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('received_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('run_reference', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('en_route_supplier', 'En route to supplier'), ('arrived', 'Arrived'), ('verifying', 'Verifying Goods'), ('en_route_warehouse', 'En route to warehouse'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('scheduled_date', models.DateField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('departed_for_supplier_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at_supplier_at', models.DateTimeField(blank=True, null=True)),
                ('collection_finished_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_runs', to='drivers.driver')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='procurement.supplier')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RunPurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.purchaseorder')),
                ('supplier_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_pos', to='procurement.supplierrun')),
            ],
        ),
        migrations.CreateModel(
            name='InboundException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(choices=[('shortfall', 'Shortfall'), ('damaged_goods', 'Damaged goods'), ('supplier_absent', 'Supplier absent'), ('wrong_goods', 'Wrong goods'), ('vehicle_issue', 'Vehicle issue'), ('delay', 'Delay')], max_length=32)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('photo_urls', models.JSONField(default=list)),
                ('resolved', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='procurement.supplierrun')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('received_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('rejected', 'Rejected')], default='good', max_length=32)),
                ('condition_notes', models.TextField(blank=True)),
                ('photo_urls', models.JSONField(default=list)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('po_line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.polineitem')),
                ('supplier_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='procurement.supplierrun')),
            ],
        ),
    ]
