# Generated by Django 5.2.12 on 2026-04-10 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSPersistence',
            fields=[
                ('persistence_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gps_persistence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_type', models.CharField(choices=[('package', 'Package'), ('pallet', 'Pallet')], default='package', max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_m3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('delivery_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('warehouse_id', models.CharField(default='WH-001', max_length=50)),
                ('warehouse_name', models.CharField(default='Main Distribution Center', max_length=100)),
                ('warehouse_address', models.TextField(default='123 Logistics Way, Industrial Zone')),
                ('warehouse_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('warehouse_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('warehouse_pickup_start', models.DateTimeField(blank=True, null=True)),
                ('warehouse_pickup_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_by_driver_id', models.IntegerField(blank=True, null=True)),
                ('delivery_location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('delivery_location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderException',
            fields=[
                ('exception_id', models.AutoField(primary_key=True, serialize=False)),
                ('exception_type', models.CharField(max_length=50)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('location_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('location_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_exceptions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'order_status_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('role_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipment_type', models.CharField(choices=[('package', 'Package'), ('pallet', 'Pallet'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('status', models.CharField(default='planned', max_length=20)),
                ('scheduled_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('leave_by_time', models.DateTimeField(blank=True, null=True)),
                ('route_sequence', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shipments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShipmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'shipment_orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_start_date', models.DateTimeField(auto_now_add=True)),
                ('assignment_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'driver_vehicle_assignments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_terms', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
    ]
