# Generated by Django 5.2.12 on 2026-04-01 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('role_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=15)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_refrigerated', models.BooleanField(default=False)),
                ('fuel_type', models.CharField(default='diesel', max_length=10)),
                ('status', models.CharField(blank=True, max_length=14, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('registration_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_terms', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50)),
                ('license_expiry_date', models.DateField()),
                ('license_type', models.CharField(default='heavy_vehicle', max_length=20)),
                ('experience_years', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('medical_certificate_expiry', models.DateField(blank=True, null=True)),
                ('last_training_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='available', max_length=20)),
                ('employee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='api.employee')),
            ],
            options={
                'db_table': 'drivers',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.role'),
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_start_date', models.DateTimeField(auto_now_add=True)),
                ('assignment_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.driverprofile')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.vehicle')),
            ],
            options={
                'db_table': 'driver_vehicle_assignments',
                'managed': True,
            },
        ),
    ]
