# Generated by Django 5.2.12 on 2026-04-10 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpspersistence',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_history', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='orderexception',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='orderexception',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='api.order'),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='api.order'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.role'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='shipmentorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_mappings', to='api.order'),
        ),
        migrations.AddField(
            model_name='shipmentorder',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_mappings', to='api.shipment'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='driver',
            field=models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vehicles.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentorder',
            unique_together={('shipment', 'order')},
        ),
    ]
