# Generated by Django 5.2.12 on 2026-04-02 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_assigned_driver_order_assigned_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipment_type', models.CharField(choices=[('package', 'Package'), ('pallet', 'Pallet'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('status', models.CharField(default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='api.driverprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='api.vehicle')),
            ],
            options={
                'db_table': 'shipments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShipmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_mappings', to='api.order')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_mappings', to='api.shipment')),
            ],
            options={
                'db_table': 'shipment_orders',
                'managed': True,
                'unique_together': {('shipment', 'order')},
            },
        ),
        migrations.DeleteModel(
            name='ShipmentDetail',
        ),
    ]
