# Generated by Django 5.2.12 on 2026-04-28 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('pod_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=150)),
                ('signature_image_url', models.TextField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pod', to='api.order')),
            ],
            options={
                'db_table': 'proof_of_delivery',
                'managed': True,
            },
        ),
    ]
