# Generated by Django 5.2.12 on 2026-04-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_proofofdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderexception',
            name='exception_type',
            field=models.CharField(choices=[('no_answer', 'No Answer'), ('address_not_found', 'Address Not Found'), ('refused', 'Refused by Customer'), ('damaged', 'Damaged in Transit'), ('traffic_delay', 'Traffic Delay'), ('vehicle_breakdown', 'Vehicle Breakdown'), ('other', 'Other')], max_length=50),
        ),
    ]
