# Generated by Django 5.2.12 on 2026-04-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouse_address',
            field=models.TextField(default='123 Logistics Way, Industrial Zone'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_id',
            field=models.CharField(default='WH-001', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_name',
            field=models.CharField(default='Main Distribution Center', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_pickup_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_pickup_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='leave_by_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='route_sequence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shipment',
            name='scheduled_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
