# Generated by Django 5.2.12 on 2026-04-08 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_warehouse_address_order_warehouse_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_by_driver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='OrderException',
            fields=[
                ('exception_id', models.AutoField(primary_key=True, serialize=False)),
                ('exception_type', models.CharField(max_length=50)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('location_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('location_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('notes', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driverprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='api.order')),
            ],
            options={
                'db_table': 'order_exceptions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=20)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='api.order')),
            ],
            options={
                'db_table': 'order_status_logs',
                'managed': True,
            },
        ),
    ]
