# Generated by Django 5.2.12 on 2026-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_orderexception_exception_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleassignment',
            name='rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
