# Generated by Django 5.2.12 on 2026-04-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_delivered_at_order_delivered_by_driver_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='employee',
        ),
    ]
