# Generated by Django 5.2.12 on 2026-05-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vehicleassignment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleassignment',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
