# Generated by Django 5.2.12 on 2026-05-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_vehicleassignment_is_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
