# Generated by Django 5.2.12 on 2026-04-09 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_driverprofile_employee'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='orderexception',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='gpspersistence',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_history', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='vehicleassignment',
            name='driver',
            field=models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='order',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicleassignment',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vehicles.vehicle'),
        ),
        migrations.DeleteModel(
            name='DriverProfile',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
