# Generated by Django 5.2.12 on 2026-05-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_recipient_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
